# -*- coding: utf-8 -*-
"""mpdet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13J6I4UPcT0kiiC99m64Sh72Nxa_a4X9f

# Startup
"""

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

!pip install wandb -qU
!pip install sklearn

!pip install wandb
import wandb
wandb.login()

"""# WANDB UTILS"""

import wandb
import seaborn as sns
import pandas as pd
from sklearn.utils.multiclass import unique_labels
from sklearn.metrics import confusion_matrix


def wandb_initialize(epochs=200, batch=46, lr=0.001, exp="untitled", q="?", v="?", h="?", N="?", pe="?", note="no note.", settings=wandb.Settings(start_method="thread")):
    wandb.init(project="THESIS_domain_adaptation_bigGPU", entity="m4x", name = exp,
            config = {
                "learning_rate": lr,
                "epoch": epochs,
                "batch_size": batch,
                "loss_function" : "sparse_categorical_crossentropy",
                "test accuracy": 0.0,
                "test loss": 0.0,
                "std accuracy": 0.0,
                "std loss": 0.0,
            },
            notes=note,
            magic=True,
    )
    return wandb.config


def show_heatmap(actual_list, predicted_list, title):
    labels = unique_labels(actual_list)
    columns = ['Predicted PP', 'Predicted PE']
    indices = ['Actual PP', 'ActualPE']
    table = pd.DataFrame(confusion_matrix(actual_list, predicted_list), columns=columns, index=indices)
    map = sns.heatmap(table, annot=True, fmt="d", cmap="viridis")

    images = wandb.Image(map, caption=title)
    wandb.log({title: images})

"""# CUSTOM LOADER"""

from numpy import dtype
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np

# CLASS: CustomDataset
# Purpose: Allows a custom dataset to be loaded into a DataLoader,
#          which is super convenient for PyTorch.
class CustomDataset(Dataset):

    def __init__(self, feature, label):
        self.data = []
        for i in range(len(feature)):
            self.data.append([feature[i], label[i]])

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        feature, label = self.data[idx]
        feature_tensor = torch.tensor(feature,  dtype=torch.float32)
        label_tensor = torch.tensor(label)
        return feature_tensor, label_tensor

"""# AUGMENTATION"""

def jitter(x, sigma=0.03):
    # https://arxiv.org/pdf/1706.00527.pdf
    return x + np.random.normal(loc=0., scale=sigma, size=x.shape)

def scaling(x, sigma=0.1):
    # https://arxiv.org/pdf/1706.00527.pdf
    factor = np.random.normal(loc=1., scale=sigma, size=(x.shape[0],x.shape[2]))
    return np.multiply(x, factor[:,np.newaxis,:])

def rotation(x):
    flip = np.random.choice([-1, 1], size=(x.shape[0],x.shape[2]))
    rotate_axis = np.arange(x.shape[2])
    np.random.shuffle(rotate_axis)
    return flip[:,np.newaxis,:] * x[:,:,rotate_axis]

def permutation(x, max_segments=5, seg_mode="equal"):
    orig_steps = np.arange(x.shape[1])

    num_segs = np.random.randint(1, max_segments, size=(x.shape[0]))

    ret = np.zeros_like(x)
    for i, pat in enumerate(x):
        if num_segs[i] > 1:
            if seg_mode == "random":
                split_points = np.random.choice(x.shape[1]-2, num_segs[i]-1, replace=False)
                split_points.sort()
                splits = np.split(orig_steps, split_points)
            else:
                splits = np.array_split(orig_steps, num_segs[i])
            warp = np.concatenate(np.random.permutation(splits)).ravel()
            ret[i] = pat[warp]
        else:
            ret[i] = pat
    return ret

def magnitude_warp(x, sigma=0.2, knot=4):
    from scipy.interpolate import CubicSpline
    orig_steps = np.arange(x.shape[1])

    random_warps = np.random.normal(loc=1.0, scale=sigma, size=(x.shape[0], knot+2, x.shape[2]))
    warp_steps = (np.ones((x.shape[2],1))*(np.linspace(0, x.shape[1]-1., num=knot+2))).T
    ret = np.zeros_like(x)
    for i, pat in enumerate(x):
        warper = np.array([CubicSpline(warp_steps[:,dim], random_warps[i,:,dim])(orig_steps) for dim in range(x.shape[2])]).T
        ret[i] = pat * warper

    return ret

"""# FILEIO

"""

import numpy as np
import pandas as pd
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
LABEL_DICT = {'PP': 0, 'PE':1}

def reshape_data(data_x, data_y):

    data_x = data_x.reshape((data_x.shape[0], data_x.shape[1], 1))
    data_y = data_y.reshape((data_y.shape[0]))

    # Shuffle the array
    idx = np.random.permutation(len(data_x))
    data_x = data_x[idx]
    data_y = data_y[idx]


    # Make the labels not strings
    data_y[data_y == -1] = 0
    data_y = np.array([LABEL_DICT[zi] for zi in data_y])

    return data_x, data_y


def load_data(path_x, path_y, csv=True):
    if(csv):
        data_x = pd.read_csv(path_x, header=0, dtype=float).to_numpy()
    else:
        data_x = pd.read_csv(path_x, header=0, dtype=float, sep='\t').to_numpy()

    data_y = pd.read_csv(path_y, header=0).to_numpy()
    return data_x, data_y


def reshape_test_data(test_x, test_y):
    test_x  = test_x.reshape((test_x.shape[0], test_x.shape[1], 1))
    test_y  = test_y.reshape((test_y.shape[0]))
    test_y[test_y == -1] == 0
    test_y = np.array([LABEL_DICT[zi] for zi in test_y])
    test_x = np.asarray(test_x).astype('float32')
    return test_x, test_y


def difference(dataset, interval=1):
        diff = []
        for i in range(interval, len(dataset)):
            value = dataset[i] - dataset[i-interval]
            diff.append(value)
        return diff


def get_norder(dataset, order, diff_val):
    differences = []
    for i in range(dataset.shape[0]):
        diff = dataset[i]
        for i in range(order):
            diff = difference(diff, interval=diff_val)
        differences.append(diff)
    differences = np.asarray(differences)
    return differences


def get_dataloader(path_x, path_y, bs, order=6, train=False, aug="none", csv=True):


    data_x, data_y = load_data(path_x, path_y)
    data_x = get_norder(data_x, order, 4)

    data_x, data_y = reshape_data(data_x, data_y)
    """if(train):
        if(aug == "jitter"):
            j = jitter(data_x)
            data_x = np.concatenate([data_x, j])
            data_y = np.concatenate([data_y, data_y])
        elif(aug == "scaling"):
            s = scaling(data_x)
            data_x = np.concatenate([data_x, s])
            data_y = np.concatenate([data_y, data_y])
        elif(aug == "mag"):
            w = magnitude_warp(data_x)
            data_x = np.concatenate([data_x, w])
            data_y = np.concatenate([data_y, data_y])
        elif(aug == "rotation"):
            r = rotation(data_x)
            data_x = np.concatenate([data_x, r])
            data_y = np.concatenate([data_y, data_y])
        elif(aug == "permutation"):
            p = permutation(data_x)
            data_x = np.concatenate([data_x, p])
            data_y = np.concatenate([data_y, data_y])
        else:
            print("no augmentation!")"""

    shape = data_x.shape[1]
    data = CustomDataset(data_x, data_y)
    return DataLoader(dataset=data, batch_size=bs, shuffle=True), shape


def get_test_dataloader(path_x, path_y, bs, order=6, csv=True):
    test_x, test_y = load_data(path_x, path_y, csv=csv)
    test_x = get_norder(test_x, order, 4)
    test_x, test_y = reshape_test_data(test_x, test_y)
    test = CustomDataset(test_x, test_y)
    return DataLoader(dataset=test, batch_size=bs, shuffle=False)

def get_augmented_standards_dataloader(path_x, path_y, bs, csv=True):
    test_x, test_y = load_data(path_x, path_y, csv=csv)
    test_x, test_y = reshape_test_data(test_x, test_y)

    # augment the data
    jit = jitter(test_x)
    scal = scaling(test_x)
    test_x = np.concatenate((test_x, jit, scal), axis=0)
    test_y = np.concatenate((test_y, test_y, test_y), axis=0)

    test_x = get_norder(test_x, 4, 4)
    test = CustomDataset(test_x, test_y)
    return DataLoader(dataset=test, batch_size=bs, shuffle=False)

"""# PYFORMER"""

import torch
import torch.nn as nn
from torch.autograd import Function
from typing import Optional
import torch.nn.functional as F
import math


# Code based on https://github.com/maxjcohen/transformer && Attention is All You Need


class Transformer(nn.Module):
    """ Transformer """
    # Initialise the Transformer
    def __init__(self,
                 d_input: int,
                 d_channel: int,
                 d_model: int,
                 d_output: int,
                 q: int,
                 v: int,
                 h: int,
                 N: int,
                 dropout: float = 0.2,
                 pe: bool = False):
        super().__init__()

        self._d_input = d_input
        self._d_channel = d_channel
        self._d_model = d_model
        self._pe = pe

        self.layers_encoding = nn.ModuleList([Encoder(d_model,
                                                      q,
                                                      v,
                                                      h,
                                                      dropout=dropout) for _ in range(N)])

        # Classificiation layer for attention outputs
        self._embedding = nn.Linear(self._d_channel, d_model)
        self._linear = nn.Linear(d_model * d_input, d_output)


    # Transformer forward pass
    def forward(self, x: torch.Tensor, grl_lambda=1.0) -> torch.Tensor:

        encoding = self._embedding(x)

        # Positional encoding
        if self._pe:
            pe = torch.ones_like(encoding[0])
            position = torch.arange(0, self._d_input).unsqueeze(-1)
            temp = torch.Tensor(range(0, self._d_model, 2))
            temp = temp * -(math.log(10000)/self._d_model)
            temp = torch.exp(temp).unsqueeze(0)
            # shape:[input, d_model/2]
            temp = torch.matmul(position.float(), temp)
            pe[:, 0::2] = torch.sin(temp)
            pe[:, 1::2] = torch.cos(temp)
            encoding = encoding + pe

        # Encoding stack
        for layer in self.layers_encoding:
            encoding = layer(encoding)

        encoding = encoding.reshape(encoding.shape[0], -1)

        output = self._linear(encoding)
        return encoding


class PositionwiseFeedForward(nn.Module):

    """ Position-wise Feed Forward Network block from Attention is All You Need. """
    def __init__(self,
                 d_model: int,
                 d_ff: Optional[int] = 2048):
        super().__init__()
        self._linear1 = nn.Linear(d_model, d_ff)
        self._linear2 = nn.Linear(d_ff, d_model)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self._linear2(F.relu(self._linear1(x)))


class MultiHeadAttention(nn.Module):
    """Multi Head Attention block from Attention is All You Need."""

    def __init__(self,
                 d_model: int,
                 q: int,
                 v: int,
                 h: int):
        super().__init__()

        self._q = q
        self._h = h

        # Query, keys and value matrices
        self._W_q = nn.Linear(d_model, q * h)
        self._W_k = nn.Linear(d_model, q * h)
        self._W_v = nn.Linear(d_model, v * h)

        # Output linear function
        self._W_o = nn.Linear(v * h, d_model)

        # Score placeholder
        self._scores = None

    def forward(self,
                query: torch.Tensor,
                key: torch.Tensor,
                value: torch.Tensor,
                mask: Optional[str] = None) -> torch.Tensor:

        # Query, keys and values
        Q = torch.cat(self._W_q(query).chunk(self._h, dim=-1), dim=0)
        K = torch.cat(self._W_k(key).chunk(self._h, dim=-1), dim=0)
        V = torch.cat(self._W_v(value).chunk(self._h, dim=-1), dim=0)

        self._scores = torch.matmul(
            Q, K.transpose(-1, -2)) / math.sqrt(self._q)  # Scaled Dot Product
        # Apply softmax: shape [batchsize * head_num, input, input]
        self._scores = F.softmax(self._scores, dim=-1)
        attention = torch.matmul(self._scores, V)  # scores * values
        attention_heads = torch.cat(attention.chunk(
            self._h, dim=0), dim=-1)  # Concatenat the heads
        # Apply linear transformation W^O shape [batchsize, input, d_model]
        self_attention = self._W_o(attention_heads)
        return self_attention


class Encoder(nn.Module):
    """Encoder block from Attention is All You Need."""

    def __init__(self,
                 d_model: int,
                 q: int,
                 v: int,
                 h: int,
                 dropout: float = 0.2):
        super().__init__()

        MHA = MultiHeadAttention
        self._selfAttention = MHA(d_model, q, v, h)
        self._feedForward = PositionwiseFeedForward(d_model)

        self._layerNorm1 = nn.LayerNorm(d_model)
        self._layerNorm2 = nn.LayerNorm(d_model)

        self._dropout = nn.Dropout(p=dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Propagate the input through the Encoder block.
        Apply the Multi Head Attention block, add residual and normalize.
        Apply the Point-wise Feed Forward block."""
        # Self attention
        residual = x
        x = self._selfAttention(query=x, key=x, value=x)
        x = self._dropout(x)
        x = self._layerNorm1(x + residual)

        # Feed forward
        residual = x
        x = self._feedForward(x)
        x = self._dropout(x)
        x = self._layerNorm2(x + residual)
        return x

"""#CORAL"""

import torch
import torch.nn as nn


class DeepCoral(nn.Module):

    def __init__(self, model ,num_classes=2):
        super(DeepCoral, self).__init__()
        self.sharedNet = model
        self.cls_fc = model._linear

    def forward(self, source, target):
        loss = 0
        source = self.sharedNet(source)
        source=source.to('cuda:0')
        target=target.to('cuda:0')
        if self.training == True:
            target = self.sharedNet(target)
            loss += CORAL(source, target)
        source = self.cls_fc(source)

        return source, loss

def CORAL(source, target):

    d = source.size(1)

    print(source, target)
    # source covariance
    xm = torch.mean(source, 0, keepdim=True) - source
    xc = xm.t() @ xm

    # target covariance
    xmt = torch.mean(target, 0, keepdim=True) - target
    xct = xmt.t() @ xmt

    # frobenius norm between source and target
    loss = torch.mean(torch.mul((xc - xct), (xc - xct)))
    loss = loss / (4 * d * d)
    return loss

"""**bold text**# BASIC TRANSFORMER

"""

import torch
import torch.nn as nn


import math


class Cryformer(nn.Module):
    def __init__(self,
                 d_input: int,
                 d_channel: int,
                 d_model: int,
                 d_output: int,
                 q: int,
                 v: int,
                 h: int,
                 N: int,
                 dropout: float = 0.3,
                 pe: bool = False):
        super().__init__()

        self._d_input = d_input
        self._d_channel = d_channel
        self._d_model = d_model
        self._pe = pe

        self.layers_encoding = nn.ModuleList([Encoder(d_model,
                                                      q,
                                                      v,
                                                      h,
                                                      dropout=dropout) for _ in range(N)])

        self._embedding = nn.Linear(self._d_channel, d_model)
        self._linear = nn.Linear(d_model * d_input, d_output)


    def forward(self, x: torch.Tensor) -> torch.Tensor:

        encoding = self._embedding(x)

        # 位置编码
        if self._pe:
            pe = torch.ones_like(encoding[0])
            position = torch.arange(0, self._d_input).unsqueeze(-1)
            temp = torch.Tensor(range(0, self._d_model, 2))
            temp = temp * -(math.log(10000)/self._d_model)
            temp = torch.exp(temp).unsqueeze(0)
            temp = torch.matmul(position.float(), temp)  # shape:[input, d_model/2]
            pe[:, 0::2] = torch.sin(temp)
            pe[:, 1::2] = torch.cos(temp)

            encoding = encoding + pe

        # Encoding stack
        for layer in self.layers_encoding:
            encoding = layer(encoding)

        # if pe:
        #     decoding = encoding + pe
        # Decoding stack
        # for layer in self.layers_decoding:
        #     decoding = layer(decoding, encoding)

        # 三维变两维
        encoding = encoding.reshape(encoding.shape[0], -1)

        # d_model -> output
        output = self._linear(encoding)

        return output


from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F


class PositionwiseFeedForward(nn.Module):
    """Position-wise Feed Forward Network block from Attention is All You Need.
    Apply two linear transformations to each input, separately but indetically. We
    implement them as 1D convolutions. Input and output have a shape (batch_size, d_model).
    Parameters
    ----------
    d_model:
        Dimension of input tensor.
    d_ff:
        Dimension of hidden layer, default is 2048.
    """

    def __init__(self,
                 d_model: int,
                 d_ff: Optional[int] = 2048):
        """Initialize the PFF block."""
        super().__init__()

        self._linear1 = nn.Linear(d_model, d_ff)
        self._linear2 = nn.Linear(d_ff, d_model)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Propagate forward the input through the PFF block.
        Apply the first linear transformation, then a relu actvation,
        and the second linear transformation.
        Parameters
        ----------
        x:
            Input tensor with shape (batch_size, K, d_model).
        Returns
        -------
            Output tensor with shape (batch_size, K, d_model).
        """
        return self._linear2(F.relu(self._linear1(x)))



from typing import Optional

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

import math


class MultiHeadAttention(nn.Module):
    """Multi Head Attention block from Attention is All You Need.
    Given 3 inputs of shape (batch_size, K, d_model), that will be used
    to compute query, keys and values, we output a self attention
    tensor of shape (batch_size, K, d_model).
    Parameters
    ----------
    d_model:
        Dimension of the input vector.
    q:
        Dimension of all query matrix.
    v:
        Dimension of all value matrix.
    h:
        Number of heads.
    attention_size:
        Number of backward elements to apply attention.
        Deactivated if ``None``. Default is ``None``.
    """

    def __init__(self,
                 d_model: int,
                 q: int,
                 v: int,
                 h: int):
        """Initialize the Multi Head Block."""
        super().__init__()

        self._q = q
        self._h = h

        # Query, keys and value matrices
        self._W_q = nn.Linear(d_model, q * h)
        self._W_k = nn.Linear(d_model, q * h)
        self._W_v = nn.Linear(d_model, v * h)

        # Output linear function
        self._W_o = nn.Linear(v * h, d_model)

        # Score placeholder
        self._scores = None

    def forward(self,
                query: torch.Tensor,
                key: torch.Tensor,
                value: torch.Tensor,
                mask: Optional[str] = None) -> torch.Tensor:

        Q = torch.cat(self._W_q(query).chunk(self._h, dim=-1), dim=0)
        K = torch.cat(self._W_k(key).chunk(self._h, dim=-1), dim=0)
        V = torch.cat(self._W_v(value).chunk(self._h, dim=-1), dim=0)
        # shape [batchsize * head_num, input, q or k or v]

        # Scaled Dot Product
        self._scores = torch.matmul(Q, K.transpose(-1, -2)) / math.sqrt(self._q)

        # Apply softmax
        self._scores = F.softmax(self._scores, dim=-1)  # shape [batchsize * head_num, input, input]

        # scores * values  结果维度(batchsize*head_nums, input, v)
        attention = torch.matmul(self._scores, V)

        # Concatenat the heads  结果维度(batchsize, input, v*head_nums)
        attention_heads = torch.cat(attention.chunk(self._h, dim=0), dim=-1)

        # Apply linear transformation W^O
        self_attention = self._W_o(attention_heads)  # shape [batchsize, input, d_model]

        return self_attention



import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F



class Encoder(nn.Module):
    """Encoder block from Attention is All You Need.
    Apply Multi Head Attention block followed by a Point-wise Feed Forward block.
    Residual sum and normalization are applied at each step.
    Parameters
    ----------
    d_model:
        Dimension of the input vector.
    q:
        Dimension of all query matrix.
    v:
        Dimension of all value matrix.
    h:
        Number of heads.
    attention_size:
        Number of backward elements to apply attention.
        Deactivated if ``None``. Default is ``None``.
    dropout:
        Dropout probability after each MHA or PFF block.
        Default is ``0.3``.
    chunk_mode:
        Swict between different MultiHeadAttention blocks.
        One of ``'chunk'``, ``'window'`` or ``None``. Default is ``'chunk'``.
    """

    def __init__(self,
                 d_model: int,
                 q: int,
                 v: int,
                 h: int,
                 dropout: float = 0.3):
        """Initialize the Encoder block"""
        super().__init__()

        MHA = MultiHeadAttention
        self._selfAttention = MHA(d_model, q, v, h)
        self._feedForward = PositionwiseFeedForward(d_model)

        # 归一化层 不过不是将数据限定在 0-1 之间或者 高斯分布（正态分布）上
        self._layerNorm1 = nn.LayerNorm(d_model)
        self._layerNorm2 = nn.LayerNorm(d_model)

        # Dropout 源码就是调用了 function中的dropout函数
        self._dropout = nn.Dropout(p=dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Propagate the input through the Encoder block.
        Apply the Multi Head Attention block, add residual and normalize.
        Apply the Point-wise Feed Forward block, add residual and normalize.
        Parameters
        ----------
        x:
            Input tensor with shape (batch_size, K, d_model).
        Returns
        -------
            Output tensor with shape (batch_size, K, d_model).
        """
        # Self attention
        residual = x
        x = self._selfAttention(query=x, key=x, value=x)
        x = self._dropout(x)
        x = self._layerNorm1(x + residual)

        # Feed forward
        residual = x
        x = self._feedForward(x)
        x = self._dropout(x)
        x = self._layerNorm2(x + residual)

        return x

"""# TRAIN DEEP CORAL

"""

import wandb
import numpy as np
import os
import torch
import torch.optim as optim
from torch import nn
import torch.nn.functional as F
import math
from torch.autograd import Variable
from google.colab import drive
import os
drive.mount('/content/drive/')

# ---------------------- #
EXPERIMENT = "DEEP CORAL 2e4 20 epoch"
NOTE = ""
# ---------------------- #

# Training data and labels
TRAIN_X, TRAIN_Y = '/content/drive/MyDrive/mpdet/data/train/train-x.csv', '/content/drive/MyDrive/mpdet/data/train/train-y.csv'
VAL_X, VAL_Y = '/content/drive/MyDrive/mpdet/data/val/val-x.csv', '/content/drive/MyDrive/mpdet/data/val/val-y.csv'
TEST_X, TEST_Y = '/content/drive/MyDrive/mpdet/data/test/test-x.csv', '/content/drive/MyDrive/mpdet/data/test/test-y.csv'
STD_X, STD_Y = '/content/drive/MyDrive/mpdet/data/standards/std-x.csv', '/content/drive/MyDrive/mpdet/data/standards/std-y.csv'


# Training Paramterers
EPOCH = 30
BATCH_SIZE = 128
LR = 3e-4
# Transformer Parameters
q = 8  # Query size
v = 8  # Value size
h = 2  # Number of heads
N = 2  # Number of encoder and decoder to stack
dropout = 0.2  # Dropout rate
pe = False  # Positional encoding


# CUDA & WANDB
DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
os.environ["WANDB_MODE"] = "online"

print(DEVICE)

def init():

    train_dataloader, shape = get_dataloader(TRAIN_X, TRAIN_Y, BATCH_SIZE)
    val_dataloader, _ = get_dataloader(VAL_X, VAL_Y, BATCH_SIZE)
    test_dataloader = get_test_dataloader(TEST_X, TEST_Y, BATCH_SIZE)
    std_dataloader = get_test_dataloader(STD_X, STD_Y, BATCH_SIZE, csv=True)

    tf = Cryformer(d_input=shape,
                                 d_channel=1,
                                 d_model=64,
                                 d_output=2,
                                 q=q,
                                 v=v,
                                 h=h,
                                 N=N,
                                 dropout=dropout, pe=pe).to(DEVICE)

    model = DeepCoral(tf).to(DEVICE)

    # Training loop
    class_loss_fn = nn.CrossEntropyLoss(reduction='mean').to(DEVICE)
    domain_loss_fn = nn.CrossEntropyLoss(reduction='mean').to(DEVICE)
    optimizer = optim.Adam(model.parameters(), lr=LR)

    # Wandb setup
    wandb.watch(model)
    wandb.config.update({'epochs': EPOCH, 'batch_size': BATCH_SIZE,
                        'lr': LR, 'q': q, 'v': v, 'h': h, 'N': N, 'pe': pe})


    # TRAINING LOOP
    for epoch in range(EPOCH):

        lossval = 0
        model.train()

        target_iter = iter(std_dataloader)  # iterate through src dataset

        for batch_idx, (src_x, src_y) in enumerate(train_dataloader):

            src_x, src_y = src_x.to(DEVICE), src_y.to(DEVICE)

            try:
                # pull out target features but ignore the labels
                trg_x, _ = next(target_iter)

            except StopIteration:
                target_iter = iter(std_dataloader)


            if src_x.shape[0] != trg_x.shape[0]:
                # if batch sizes are different, skip this batch
                continue

            trg_x = trg_x.to(DEVICE)

            optimizer.zero_grad()

            src_pred, coral_loss = model(src_x, trg_x)
            print(coral_loss)
            cls_loss = F.nll_loss(F.log_softmax(src_pred, dim=1), src_y)
            lambd = 2 / (1 + math.exp(-10 * (epoch) / EPOCH)) - 1
            loss = cls_loss + lambd * coral_loss
            loss.backward()
            optimizer.step()

            # Run validation set and target set through validation loop to see performance
            val_acc = test(model, val_dataloader, "val")
            std_acc = test(model, std_dataloader, "std")

    test_acc = test(model, test_dataloader, "test")

    #test_acc = test_network(model, test_dataloader, class_loss_fn, "test")
    #print("Final test set accuracy: {}%".format(test_acc))


def test(model, tgt_test_loader, flag):
    model.eval()
    test_loss = 0
    correct = 0

    with torch.no_grad():
        for tgt_test_data, tgt_test_label in tgt_test_loader:
            tgt_test_data = tgt_test_data.to(DEVICE)
            tgt_test_label = tgt_test_label.to(DEVICE)
            tgt_test_data, tgt_test_label = Variable(tgt_test_data), Variable(tgt_test_label)
            tgt_pred, coral_loss = model(tgt_test_data, tgt_test_data)
            test_loss += F.nll_loss(F.log_softmax(tgt_pred, dim = 1), tgt_test_label, reduction='sum').item() # sum up batch loss
            pred = tgt_pred.data.max(1)[1] # get the index of the max log-probability
            correct += pred.eq(tgt_test_label.data.view_as(pred)).cpu().sum()

    test_loss /= len(tgt_test_loader.dataset)
    print('Test set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(test_loss, correct, len(tgt_test_loader.dataset),100. * correct / len(tgt_test_loader.dataset)))

     # Send testing info to wandb
    loss_log = flag + ' loss'
    acc_log = flag + ' accuracy'
    wandb.log({loss_log: test_loss})
    wandb.log({acc_log: 100 *  correct / len(tgt_test_loader.dataset)})
    wandb.config.update({acc_log: 100 *  correct / len(tgt_test_loader.dataset)},
                        allow_val_change=True)
    wandb.config.update({loss_log: test_loss},allow_val_change=True)

    #show_heatmap(actual_list, predicted_list, "test cm")
    return 100 *  correct / len(tgt_test_loader.dataset)




def test_network(model, dataloader, loss_fn=None, flag='test'):

    predicted_list, actual_list = [], []
    correct, total, lossval = 0, 0, 0

    model.eval()  # Put model into evaluation mode and disable gradient calculation
    with torch.no_grad():
        for x, y in dataloader:

            x, y = x.to(DEVICE), y.to(DEVICE)  # send to CUDA / CPU
            pred = model.predict(x)  # ignore domain prediction
            # Calculate loss w features and labels
            test_loss = F.nll_loss(F.log_softmax(pred, dim=1), y).item()
            lossval += test_loss  # Tally up the loss
            # Store the class predictions made by the model
            pred = pred.data.max(1)[1]
            predicted_list += pred.tolist()
            actual_list += y.tolist()
            total += y.size(0)
            correct += (pred.float() == y.float()).sum().item()
            print("1")

    # Send testing info to wandb
    loss_log = flag + ' loss'
    acc_log = flag + ' accuracy'
    wandb.log({loss_log: lossval/len(dataloader)})
    wandb.log({acc_log: 100 * correct // total})
    wandb.config.update({acc_log: 100 * correct / total},
                        allow_val_change=True)
    wandb.config.update({loss_log: lossval/len(dataloader)},
                        allow_val_change=True)

    #show_heatmap(actual_list, predicted_list, "test cm")
    return 100 * correct / total


config = wandb_initialize( EPOCH, BATCH_SIZE, LR, EXPERIMENT, q, v, h, N, pe, NOTE)

if __name__ == "__main__":
    init()



"""# Default


"""

wandb.init(project="THESIS_differencing", entity="m4x", name = "hyperparam tuning")

# Example sweep configuration
sweep_configuration = {
    'method': 'grid',
    'name': 'sweep',
    'metric': {
        'goal': 'maximize',
        'name': 'val acc'
		},
    'parameters': {
        'batch_size': {'values': [128]},
        'epochs': {'values': [25]},
        'lr': {'values': [0.0003]},
        'order': {'values': [1,2,3,4,5,6]},
        'dim': {'values': [64,512,1024]}
    }
}

sweep_id = wandb.sweep(sweep=sweep_configuration, project="THESIS_differencing")


def build_optimizer(network, optimizer, learning_rate):
    if optimizer == "sgd":
        optimizer = optim.SGD(network.parameters(),
                              lr=learning_rate, momentum=0.9)
    elif optimizer == "adam":
        optimizer = optim.Adam(network.parameters(),
                               lr=learning_rate)
    return optimizer


def build_network(cdropout, ch, cN, shape):
    model = Cryformer(d_input=shape,
                                 d_channel=1,
                                 d_model=64,
                                 d_output=2,
                                 q=q,
                                 v=v,
                                 h=ch,
                                 N=cN,
                                 dropout=cdropout, pe=False).to(DEVICE)

    return model.to(DEVICE)

import wandb
import numpy as np
import os
import torch
import torch.optim as optim
from torch import nn
import torch.nn.functional as F
import math
from torch.autograd import Variable
from google.colab import drive
import os
from sklearn.metrics import classification_report, confusion_matrix

drive.mount('/content/drive/')

# ---------------------- #
EXPERIMENT = "Differencing"
NOTE = ""
# ---------------------- #

# Training data and labels
TRAIN_X, TRAIN_Y = '/content/drive/MyDrive/mpdet/data/train/train-x.csv', '/content/drive/MyDrive/mpdet/data/train/train-y.csv'
VAL_X, VAL_Y = '/content/drive/MyDrive/mpdet/data/val/val-x.csv', '/content/drive/MyDrive/mpdet/data/val/val-y.csv'
TEST_X, TEST_Y = '/content/drive/MyDrive/mpdet/data/test/test-x.csv', '/content/drive/MyDrive/mpdet/data/test/test-y.csv'
STD_X, STD_Y = '/content/drive/MyDrive/mpdet/data/standards/std-x.csv', '/content/drive/MyDrive/mpdet/data/standards/std-y.csv'


# Training Paramterers

# Transformer Parameters
q = 8  # Query size
v = 8  # Value size
h = 2  # Number of heads
N = 2  # Number of encoder and decoder to stack
dropout = 0.2  # Dropout rate
pe = False  # Positional encoding


# CUDA & WANDB
DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
os.environ["WANDB_MODE"] = "online"

print(DEVICE)

def init(config=None):


    with wandb.init(config=config):


        config = wandb.config
        print("BATCH SIZE")
        print(config.batch_size)
        train_dataloader, shape = get_dataloader(TRAIN_X, TRAIN_Y, config.batch_size, config.order, train=True)
        val_dataloader, _ = get_dataloader(VAL_X, VAL_Y,  config.batch_size, config.order)
        test_dataloader = get_test_dataloader(TEST_X, TEST_Y,  config.batch_size, config.order)
        std_dataloader = get_test_dataloader(STD_X, STD_Y, config.batch_size, config.order, csv=True)

        # If called by wandb.agent, as below,
        # this config will be set by Sweep Controller
        model = build_network(0.2, 2, 2, shape)
        loss_fn = nn.CrossEntropyLoss(reduction='mean').to(DEVICE)
        optimizer = build_optimizer(model, 'adam', config.lr)

        for epoch in range(config.epochs):
            lossval = 0
            model.train()
            for batch_idx, (x, batch_y) in enumerate(train_dataloader):
                x, batch_y = x.to(DEVICE), batch_y.to(DEVICE)
                optimizer.zero_grad()
                out = model(x.to(DEVICE))
                loss = loss_fn(out, batch_y.to(DEVICE))
                loss.backward()
                optimizer.step()
                lossval += loss.item()


            test_the_network(model, val_dataloader,  loss_fn, flag="val_set")
            test_the_network(model, std_dataloader,  loss_fn, flag="std_set")

        print("====  TEST SET  ====")
        predicted, y_test = test_the_network(model, test_dataloader,  loss_fn, flag="test_set")
        print(classification_report(y_test, predicted))
        print(confusion_matrix(y_test, predicted, labels=["PE","PP"]))
        print("\n\n====  STD SET  ====")
        predicted, y_test = test_the_network(model, std_dataloader,  loss_fn, flag="std_set")
        print(classification_report(y_test, predicted))
        print(confusion_matrix(y_test, predicted, labels=["PE","PP"]))
        print()
        #print("Final test set accuracy: {}%".format(test_acc))


def test_the_network(net, dataloader_test, lossy=None, flag='test_set'):

    correct, total, lossval = 0.0, 0, 0
    predicted_list, actual_list = [], []
    # Testing loop
    with torch.no_grad():
        for x_test, y_test in dataloader_test:
            enc_inputs, dec_inputs = x_test.to(DEVICE), y_test.to(DEVICE)
            test_outputs = net(enc_inputs)
            loss = lossy(test_outputs, dec_inputs)
            lossval += loss.item()
            _, predicted = torch.max(test_outputs.data, dim=1)
            predicted_list += predicted.tolist()
            actual_list += y_test.tolist()
            total += dec_inputs.size(0)
            correct += (predicted.float() == dec_inputs.float()).sum().item()

    if flag == "val_set":
        val_test(dataloader_test, correct, total, lossval)
    elif flag == "std_set":
        std_test(dataloader_test, correct, total, lossval)
    else:
        test_test(dataloader_test, correct, total, lossval)

    return predicted_list, actual_list


def val_test(dataloader_test, correct, total, lossval):
    print("val loss: ", lossval/len(dataloader_test))
    print("val acc: ", 100 * correct // total)
    wandb.log({'val loss': lossval/len(dataloader_test)})
    wandb.log({'val accuracy': 100 * correct // total})

def test_test(dataloader_test, correct, total, lossval):
    print("test acc: ", 100 * correct / total)
    wandb.log({'test loss': lossval/len(dataloader_test)})
    wandb.log({'test acc': 100 * correct // total})
    wandb.config.update({'test accuracy': 100 * correct / total})
    wandb.config.update({'test loss': lossval/len(dataloader_test)})

    #show_heatmap(actual_list, predicted_list, "test cm")

def std_test(dataloader_test, correct, total, lossval):
    print("std acc: ", 100 * correct / total)
    wandb.config.update({'std accuracy': 100 * correct / total}, allow_val_change=True)
    wandb.config.update({'std loss': lossval/len(dataloader_test)}, allow_val_change=True)
    wandb.log({'std loss': lossval/len(dataloader_test)})
    wandb.log({'std acc': 100 * correct // total})


if __name__ == "__main__":
    wandb.agent(sweep_id, init, count=10)

"""# Differencing Testing

"""

# Example sweep configuration
sweep_configuration = {
    'method': 'grid',
    'name': 'sweep',
    'metric': {
        'goal': 'maximize',
        'name': 'val accuracy'
		},
    'parameters': {
        'order': {
            'values': [0,1,2,3,4,5,6]
        },
     }
}

sweep_id = wandb.sweep(sweep=sweep_configuration, project="THESIS_default_transformer")



def build_optimizer(network, optimizer, learning_rate):
    if optimizer == "sgd":
        optimizer = optim.SGD(network.parameters(),
                              lr=learning_rate, momentum=0.9)
    elif optimizer == "adam":
        optimizer = optim.Adam(network.parameters(),
                               lr=learning_rate)
    return optimizer


def build_network(cdropout, ch, cN, shape):
    model = Cryformer(d_input=shape,
                                 d_channel=1,
                                 d_model=64,
                                 d_output=2,
                                 q=q,
                                 v=v,
                                 h=ch,
                                 N=cN,
                                 dropout=cdropout, pe=False).to(DEVICE)

    return model.to(DEVICE)

import wandb
import numpy as np
import os
import torch
import torch.optim as optim
from torch import nn
import torch.nn.functional as F
import math
from torch.autograd import Variable
from google.colab import drive
import os
from sklearn.metrics import classification_report

drive.mount('/content/drive/')

# ---------------------- #
EXPERIMENT = "Default Transformer"
NOTE = ""
# ---------------------- #

# Training data and labels
TRAIN_X, TRAIN_Y = '/content/drive/MyDrive/mpdet/data/train/train-x.csv', '/content/drive/MyDrive/mpdet/data/train/train-y.csv'
VAL_X, VAL_Y = '/content/drive/MyDrive/mpdet/data/val/val-x.csv', '/content/drive/MyDrive/mpdet/data/val/val-y.csv'
TEST_X, TEST_Y = '/content/drive/MyDrive/mpdet/data/test/test-x.csv', '/content/drive/MyDrive/mpdet/data/test/test-y.csv'
STD_X, STD_Y = '/content/drive/MyDrive/mpdet/data/standards/std-x.csv', '/content/drive/MyDrive/mpdet/data/standards/std-y.csv'


# Training Paramterers

# Transformer Parameters
q = 8  # Query size
v = 8  # Value size
h = 2  # Number of heads
N = 2  # Number of encoder and decoder to stack
dropout = 0.2  # Dropout rate
pe = False  # Positional encoding


# CUDA & WANDB
DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
os.environ["WANDB_MODE"] = "online"

print(DEVICE)

def init(config=None):


    with wandb.init(config=config):


        config = wandb.config
        print("BATCH SIZE")
        train_dataloader, shape = get_dataloader(TRAIN_X, TRAIN_Y, 64, order=config.order)
        val_dataloader, _ = get_dataloader(VAL_X, VAL_Y,  64, order=config.order)
        test_dataloader = get_test_dataloader(TEST_X, TEST_Y,  64, order=config.order)
        std_dataloader = get_test_dataloader(STD_X, STD_Y, 64,order=config.order, csv=True)

        # If called by wandb.agent, as below,
        # this config will be set by Sweep Controller
        model = build_network(0.2, 2, 2, shape)
        loss_fn = nn.CrossEntropyLoss(reduction='mean').to(DEVICE)
        optimizer = build_optimizer(model, 'adam', 0.0005)

        for epoch in range(25):
            lossval = 0
            model.train()
            for batch_idx, (x, batch_y) in enumerate(train_dataloader):
                x, batch_y = x.to(DEVICE), batch_y.to(DEVICE)
                optimizer.zero_grad()
                out = model(x.to(DEVICE))
                loss = loss_fn(out, batch_y.to(DEVICE))
                loss.backward()
                optimizer.step()
                lossval += loss.item()


            test_the_network(model, val_dataloader,  loss_fn, flag="val_set")
            test_the_network(model, std_dataloader,  loss_fn, flag="std_set")

    print("====  TEST SET  ====")
    predicted, y_test = test_the_network(model, test_dataloader,  loss_fn, flag="test_set")
    print(classification_report(y_test, predicted))
    print("\n\n====  STD SET  ====")
    predicted, y_test = test_the_network(model, std_dataloader,  loss_fn, flag="std_set")
    print(classification_report(y_test, predicted))
    #print("Final test set accuracy: {}%".format(test_acc))


def test_the_network(net, dataloader_test, lossy=None, flag='test_set'):

    correct, total, lossval = 0.0, 0, 0
    predicted_list, actual_list = [], []
    # Testing loop
    with torch.no_grad():
        for x_test, y_test in dataloader_test:
            enc_inputs, dec_inputs = x_test.to(DEVICE), y_test.to(DEVICE)
            test_outputs = net(enc_inputs)
            loss = lossy(test_outputs, dec_inputs)
            lossval += loss.item()
            _, predicted = torch.max(test_outputs.data, dim=1)
            predicted_list += predicted.tolist()
            actual_list += y_test.tolist()
            total += dec_inputs.size(0)
            correct += (predicted.float() == dec_inputs.float()).sum().item()

    if flag == "val_set":
        val_test(dataloader_test, correct, total, lossval)
    elif flag == "std_set":
        std_test(dataloader_test, correct, total, lossval)
    else:
        test_test(dataloader_test, correct, total, lossval)

    return predicted_list, actual_list


def val_test(dataloader_test, correct, total, lossval):
    print("val loss: ", lossval/len(dataloader_test))
    print("val acc: ", 100 * correct // total)
    wandb.log({'val loss': lossval/len(dataloader_test)})
    wandb.log({'val accuracy': 100 * correct // total})

def test_test(dataloader_test, correct, total, lossval):
    print("test acc: ", 100 * correct / total)
    wandb.config.update({'test accuracy': 100 * correct / total})
    wandb.config.update({'test loss': lossval/len(dataloader_test)})
    #show_heatmap(actual_list, predicted_list, "test cm")

def std_test(dataloader_test, correct, total, lossval):
    wandb.config.update({'std accuracy': 100 * correct / total}, allow_val_change=True)
    wandb.config.update({'std loss': lossval/len(dataloader_test)}, allow_val_change=True)
    wandb.log({'std loss': lossval/len(dataloader_test)})
    wandb.log({'std acc': 100 * correct // total})


if __name__ == "__main__":
    wandb.agent(sweep_id, init, count=10)

"""# DSAN

## DSAN Transformer
"""

import torch
import torch.nn as nn
from torch.autograd import Function
from typing import Optional
import torch.nn.functional as F
import math


# Code based on https://github.com/maxjcohen/transformer && Attention is All You Need

# Gradient reversal class for DANN domain adaptation
class GradientReversalFunction(Function):
    @staticmethod
    def forward(ctx, x, alpha):
        ctx.alpha = alpha
        return x

    @staticmethod
    def backward(ctx, grad_output):
        return -ctx.alpha * grad_output, None


class Dsanformer(nn.Module):
    """ Transformer """
    # Initialise the Transformer
    def __init__(self,
                 d_input: int,
                 d_channel: int,
                 d_model: int,
                 d_output: int,
                 q: int,
                 v: int,
                 h: int,
                 N: int,
                 dropout: float = 0.3,
                 pe: bool = False):
        super().__init__()

        self._d_input = d_input
        self._d_channel = d_channel
        self._d_model = d_model
        self._pe = pe

        self.layers_encoding = nn.ModuleList([Encoder(d_model,
                                                      q,
                                                      v,
                                                      h,
                                                      dropout=dropout) for _ in range(N)])

        # Classificiation layer for attention outputs
        self._embedding = nn.Linear(self._d_channel, d_model)
        self._linear = nn.Linear(d_model * d_input, d_output)


    # Transformer forward pass
    def forward(self, x: torch.Tensor, grl_lambda=1.0) -> torch.Tensor:

        encoding = self._embedding(x)

        # Positional encoding
        if self._pe:
            pe = torch.ones_like(encoding[0])
            position = torch.arange(0, self._d_input).unsqueeze(-1)
            temp = torch.Tensor(range(0, self._d_model, 2))
            temp = temp * -(math.log(10000)/self._d_model)
            temp = torch.exp(temp).unsqueeze(0)
            # shape:[input, d_model/2]
            temp = torch.matmul(position.float(), temp)
            pe[:, 0::2] = torch.sin(temp)
            pe[:, 1::2] = torch.cos(temp)
            encoding = encoding + pe

        # Encoding stack
        for layer in self.layers_encoding:
            encoding = layer(encoding)

        encoding = encoding.reshape(encoding.shape[0], -1)

        return encoding


class PositionwiseFeedForward(nn.Module):

    """ Position-wise Feed Forward Network block from Attention is All You Need. """
    def __init__(self,
                 d_model: int,
                 d_ff: Optional[int] = 2048):
        super().__init__()
        self._linear1 = nn.Linear(d_model, d_ff)
        self._linear2 = nn.Linear(d_ff, d_model)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self._linear2(F.relu(self._linear1(x)))


class MultiHeadAttention(nn.Module):
    """Multi Head Attention block from Attention is All You Need."""

    def __init__(self,
                 d_model: int,
                 q: int,
                 v: int,
                 h: int):
        super().__init__()

        self._q = q
        self._h = h

        # Query, keys and value matrices
        self._W_q = nn.Linear(d_model, q * h)
        self._W_k = nn.Linear(d_model, q * h)
        self._W_v = nn.Linear(d_model, v * h)

        # Output linear function
        self._W_o = nn.Linear(v * h, d_model)

        # Score placeholder
        self._scores = None

    def forward(self,
                query: torch.Tensor,
                key: torch.Tensor,
                value: torch.Tensor,
                mask: Optional[str] = None) -> torch.Tensor:

        # Query, keys and values
        Q = torch.cat(self._W_q(query).chunk(self._h, dim=-1), dim=0)
        K = torch.cat(self._W_k(key).chunk(self._h, dim=-1), dim=0)
        V = torch.cat(self._W_v(value).chunk(self._h, dim=-1), dim=0)

        self._scores = torch.matmul(
            Q, K.transpose(-1, -2)) / math.sqrt(self._q)  # Scaled Dot Product
        # Apply softmax: shape [batchsize * head_num, input, input]
        self._scores = F.softmax(self._scores, dim=-1)
        attention = torch.matmul(self._scores, V)  # scores * values
        attention_heads = torch.cat(attention.chunk(
            self._h, dim=0), dim=-1)  # Concatenat the heads
        # Apply linear transformation W^O shape [batchsize, input, d_model]
        self_attention = self._W_o(attention_heads)
        return self_attention


class Encoder(nn.Module):
    """Encoder block from Attention is All You Need."""

    def __init__(self,
                 d_model: int,
                 q: int,
                 v: int,
                 h: int,
                 dropout: float = 0.3):
        super().__init__()

        MHA = MultiHeadAttention
        self._selfAttention = MHA(d_model, q, v, h)
        self._feedForward = PositionwiseFeedForward(d_model)

        self._layerNorm1 = nn.LayerNorm(d_model)
        self._layerNorm2 = nn.LayerNorm(d_model)

        self._dropout = nn.Dropout(p=dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Propagate the input through the Encoder block.
        Apply the Multi Head Attention block, add residual and normalize.
        Apply the Point-wise Feed Forward block."""
        # Self attention
        residual = x
        x = self._selfAttention(query=x, key=x, value=x)
        x = self._dropout(x)
        x = self._layerNorm1(x + residual)

        # Feed forward
        residual = x
        x = self._feedForward(x)
        x = self._dropout(x)
        x = self._layerNorm2(x + residual)
        return

"""## DSAN Model"""

class DSAN(nn.Module):

    def __init__(self, model, num_classes=2, bottle_neck=True):
        super(DSAN, self).__init__()
        self.feature_layers = model
        self.lmmd_loss = LMMD_loss(class_num=num_classes)
        self.cls_fc = model._linear

    def forward(self, source, target, s_label):
        source = self.feature_layers(source)
        s_pred = self.feature_layers._linear(source)

        target = self.feature_layers(target)
        t_label = self.cls_fc(target)
        loss_lmmd = self.lmmd_loss.get_loss(source, target, s_label, torch.nn.functional.softmax(t_label, dim=1))
        return s_pred, loss_lmmd

    def predict(self, x):
        x = self.feature_layers(x)

        return self.cls_fc(x)




import torch
import torch.nn as nn
import numpy as np

class LMMD_loss(nn.Module):
    def __init__(self, class_num=31, kernel_type='rbf', kernel_mul=2.0, kernel_num=5, fix_sigma=None):
        super(LMMD_loss, self).__init__()
        self.class_num = class_num
        self.kernel_num = kernel_num
        self.kernel_mul = kernel_mul
        self.fix_sigma = fix_sigma
        self.kernel_type = kernel_type

    def guassian_kernel(self, source, target, kernel_mul=2.0, kernel_num=5, fix_sigma=None):
        n_samples = int(source.size()[0]) + int(target.size()[0])
        total = torch.cat([source, target], dim=0)
        total0 = total.unsqueeze(0).expand(
            int(total.size(0)), int(total.size(0)), int(total.size(1)))
        total1 = total.unsqueeze(1).expand(
            int(total.size(0)), int(total.size(0)), int(total.size(1)))
        L2_distance = ((total0-total1)**2).sum(2)
        if fix_sigma:
            bandwidth = fix_sigma
        else:
            bandwidth = torch.sum(L2_distance.data) / (n_samples**2-n_samples)
        bandwidth /= kernel_mul ** (kernel_num // 2)
        bandwidth_list = [bandwidth * (kernel_mul**i)
                          for i in range(kernel_num)]
        kernel_val = [torch.exp(-L2_distance / bandwidth_temp)
                      for bandwidth_temp in bandwidth_list]
        return sum(kernel_val)

    def get_loss(self, source, target, s_label, t_label):
        batch_size = source.size()[0]
        weight_ss, weight_tt, weight_st = self.cal_weight(
            s_label, t_label, batch_size=batch_size, class_num=self.class_num)
        weight_ss = torch.from_numpy(weight_ss).cuda()
        weight_tt = torch.from_numpy(weight_tt).cuda()
        weight_st = torch.from_numpy(weight_st).cuda()

        kernels = self.guassian_kernel(source, target,
                                kernel_mul=self.kernel_mul, kernel_num=self.kernel_num, fix_sigma=self.fix_sigma)
        loss = torch.Tensor([0]).cuda()
        if torch.sum(torch.isnan(sum(kernels))):
            return loss
        SS = kernels[:batch_size, :batch_size]
        TT = kernels[batch_size:, batch_size:]
        ST = kernels[:batch_size, batch_size:]

        loss += torch.sum(weight_ss * SS + weight_tt * TT - 2 * weight_st * ST)
        return loss

    def convert_to_onehot(self, sca_label, class_num=31):
        return np.eye(class_num)[sca_label]

    def cal_weight(self, s_label, t_label, batch_size=32, class_num=31):
        batch_size = s_label.size()[0]
        s_sca_label = s_label.cpu().data.numpy()
        s_vec_label = self.convert_to_onehot(s_sca_label, class_num=self.class_num)
        s_sum = np.sum(s_vec_label, axis=0).reshape(1, class_num)
        s_sum[s_sum == 0] = 100
        s_vec_label = s_vec_label / s_sum

        t_sca_label = t_label.cpu().data.max(1)[1].numpy()
        t_vec_label = t_label.cpu().data.numpy()
        t_sum = np.sum(t_vec_label, axis=0).reshape(1, class_num)
        t_sum[t_sum == 0] = 100
        t_vec_label = t_vec_label / t_sum

        index = list(set(s_sca_label) & set(t_sca_label))
        mask_arr = np.zeros((batch_size, class_num))
        mask_arr[:, index] = 1
        t_vec_label = t_vec_label * mask_arr
        s_vec_label = s_vec_label * mask_arr

        weight_ss = np.matmul(s_vec_label, s_vec_label.T)
        weight_tt = np.matmul(t_vec_label, t_vec_label.T)
        weight_st = np.matmul(s_vec_label, t_vec_label.T)

        length = len(index)
        if length != 0:
            weight_ss = weight_ss / length
            weight_tt = weight_tt / length
            weight_st = weight_st / length
        else:
            weight_ss = np.array([0])
            weight_tt = np.array([0])
            weight_st = np.array([0])
        return weight_ss.astype('float32'), weight_tt.astype('float32'), weight_st.astype('float32')

"""## DSAN Train

"""

import numpy as np
from google.colab import drive

import os
import torch
import torch.optim as optim
from torch import nn
import torch.nn.functional as F
import math
# ---------------------- #
EXPERIMENT = "DSAN"
NOTE = ""
# ---------------------- #
drive.mount('/content/drive/')


# Training data and labels
TRAIN_X, TRAIN_Y = '/content/drive/MyDrive/mpdet/data/train/train-x.csv', '/content/drive/MyDrive/mpdet/data/train/train-y.csv'
VAL_X, VAL_Y = '/content/drive/MyDrive/mpdet/data/val/val-x.csv', '/content/drive/MyDrive/mpdet/data/val/val-y.csv'
TEST_X, TEST_Y = '/content/drive/MyDrive/mpdet/data/test/test-x.csv', '/content/drive/MyDrive/mpdet/data/test/test-y.csv'
STD_X, STD_Y = '/content/drive/MyDrive/mpdet/data/standards/std-x.csv', '/content/drive/MyDrive/mpdet/data/standards/std-y.csv'


# Training Paramterers
EPOCH = 20
BATCH_SIZE = 64
LR = 2e-4
# Transformer Parameters
q = 8  # Query size
v = 8  # Value size
h = 2  # Number of heads
N = 2  # Number of encoder and decoder to stack
dropout = 0.2  # Dropout rate
pe = False  # Positional encoding


# CUDA & WANDB
DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
os.environ["WANDB_MODE"] = "online"


def init():

    train_dataloader, shape = get_dataloader(TRAIN_X, TRAIN_Y, BATCH_SIZE)
    val_dataloader, _ = get_dataloader(VAL_X, VAL_Y, BATCH_SIZE)
    test_dataloader = get_test_dataloader(TEST_X, TEST_Y, BATCH_SIZE)
    std_dataloader = get_test_dataloader(STD_X, STD_Y, BATCH_SIZE, csv=True)

    tf = Dsanformer(d_input=shape,
                                 d_channel=1,
                                 d_model=64,
                                 d_output=2,
                                 q=q,
                                 v=v,
                                 h=h,
                                 N=N,
                                 dropout=dropout, pe=pe).to(DEVICE)

    model = DSAN(tf, num_classes=2).to(DEVICE)

    # Training loop
    class_loss_fn = nn.CrossEntropyLoss(reduction='mean').to(DEVICE)
    domain_loss_fn = nn.CrossEntropyLoss(reduction='mean').to(DEVICE)
    optimizer = optim.Adam(model.parameters(), lr=LR)

    # Wandb setup
    wandb.watch(model)
    wandb.config.update({'epochs': EPOCH, 'batch_size': BATCH_SIZE,
                        'lr': LR, 'q': q, 'v': v, 'h': h, 'N': N, 'pe': pe})

    # TRAINING LOOP
    for epoch in range(EPOCH):

        lossval = 0
        model.train()

        target_iter = iter(std_dataloader)  # iterate through src dataset

        for batch_idx, (src_x, src_y) in enumerate(train_dataloader):

            src_x, src_y = src_x.to(DEVICE), src_y.to(DEVICE)
            try:
                # pull out target features but ignore the labels
                trg_x, _ = next(target_iter)

            except StopIteration:
                target_iter = iter(std_dataloader)


            if src_x.shape[0] != trg_x.shape[0]:
                # if batch sizes are different, skip this batch
                continue

            trg_x = trg_x.to(DEVICE)

            optimizer.zero_grad()
            print(trg_x, "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")

            label_source_pred, loss_lmmd = model(src_x, trg_x, src_y)

            loss_cls = F.nll_loss(F.log_softmax(label_source_pred, dim=1), src_y)
            lambd = 2 / (1 + math.exp(-10 * (epoch) / EPOCH)) - 1
            loss = loss_cls + 0.5 * lambd * loss_lmmd
            # log the loss
            wandb.log({'loss': loss.item()})
            loss.backward()
            optimizer.step()


            # Run validation set and target set through validation loop to see performance
            val_acc = test_network(model, val_dataloader,
                                   class_loss_fn, "val")
            std_acc = test_network(model, std_dataloader,
                                   class_loss_fn, "std")

    #test_acc = test_network(model, test_dataloader,
    #           class_loss_fn, "test")"""
    #print("Final test set accuracy: {}%".format(test_acc))



def test(model, tgt_test_loader, flag):
    model.eval()
    test_loss = 0
    correct = 0

    with torch.no_grad():
        for tgt_test_data, tgt_test_label in tgt_test_loader:
            tgt_test_data = tgt_test_data.to(DEVICE)
            tgt_test_label = tgt_test_label.to(DEVICE)
            tgt_test_data, tgt_test_label = Variable(tgt_test_data), Variable(tgt_test_label)
            tgt_pred, coral_loss = model(tgt_test_data, tgt_test_data)
            test_loss += F.nll_loss(F.log_softmax(tgt_pred, dim = 1), tgt_test_label, reduction='sum').item() # sum up batch loss
            pred = tgt_pred.data.max(1)[1] # get the index of the max log-probability
            correct += pred.eq(tgt_test_label.data.view_as(pred)).cpu().sum()

    test_loss /= len(tgt_test_loader.dataset)
    print('Test set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(test_loss, correct, len(tgt_test_loader.dataset),100. * correct / len(tgt_test_loader.dataset)))

     # Send testing info to wandb
    loss_log = flag + ' loss'
    acc_log = flag + ' accuracy'
    wandb.log({loss_log: test_loss})
    wandb.log({acc_log: 100 *  correct / len(tgt_test_loader.dataset)})
    wandb.config.update({acc_log: 100 *  correct / len(tgt_test_loader.dataset)},
                        allow_val_change=True)
    wandb.config.update({loss_log: test_loss},allow_val_change=True)

    #show_heatmap(actual_list, predicted_list, "test cm")
    return 100 *  correct / len(tgt_test_loader.dataset)


def test_network(model, dataloader, loss_fn=None, flag='test'):

    predicted_list, actual_list = [], []
    correct, total, lossval = 0, 0, 0

    model.eval()  # Put model into evaluation mode and disable gradient calculation
    with torch.no_grad():
        for x, y in dataloader:

            x, y = x.to(DEVICE), y.to(DEVICE)  # send to CUDA / CPU
            pred = model.predict(x)  # ignore domain prediction
            # Calculate loss w features and labels
            test_loss = F.nll_loss(F.log_softmax(pred, dim=1), y).item()
            lossval += test_loss  # Tally up the loss
            # Store the class predictions made by the model
            pred = pred.data.max(1)[1]
            predicted_list += pred.tolist()
            actual_list += y.tolist()
            total += y.size(0)
            correct += (pred.float() == y.float()).sum().item()

    # Send testing info to wandb
    loss_log = flag + ' loss'
    acc_log = flag + ' accuracy'
    wandb.log({loss_log: lossval/len(dataloader)})
    wandb.log({acc_log: 100 * correct // total})
    wandb.config.update({acc_log: 100 * correct / total},
                        allow_val_change=True)
    wandb.config.update({loss_log: lossval/len(dataloader)},
                        allow_val_change=True)

    #show_heatmap(actual_list, predicted_list, "test cm")
    return 100 * correct / total


config = wandb_initialize(
    EPOCH, BATCH_SIZE, LR, EXPERIMENT, q, v, h, N, pe, NOTE)

if __name__ == "__main__":
    init()